name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vulkan
      run: |
        curl https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe --output vulkan-sdk.exe
        ./vulkan-sdk.exe /S

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build
      run: cmake --build .build/

    - name: Test
      run: |
        cd .build/
        ctest .